import { bi, type Bi } from "@/lib/i18n";

export type KpiStatus = "green" | "amber" | "red" | "na" | "review";
export const kpiStatuses: KpiStatus[] = ["green", "amber", "red", "na", "review"];

export type Kpi = {
  id: string;
  title: Bi;
  purpose: Bi;
  source: Bi;
  frequency: Bi;
  target: Bi;
};

export type KpiArea = { id: string; title: Bi; description: Bi; kpis: Kpi[] };

const k = (
  id: string,
  titleSr: string,
  titleEn: string,
  purposeSr: string,
  purposeEn: string,
  sourceSr: string,
  sourceEn: string,
  freqSr: string,
  freqEn: string,
  targetSr: string,
  targetEn: string,
): Kpi => ({
  id,
  title: bi(titleSr, titleEn),
  purpose: bi(purposeSr, purposeEn),
  source: bi(sourceSr, sourceEn),
  frequency: bi(freqSr, freqEn),
  target: bi(targetSr, targetEn),
});

export const kpiAreas: KpiArea[] = [
  {
    id: "1",
    title: bi("Uptake ORRI alata", "ORRI Tool Uptake"),
    description: bi(
      "Da li se alat zapravo koristi u relevantnim projektima.",
      "Whether the tool is actually used in relevant projects.",
    ),
    kpis: [
      k(
        "1.1",
        "Broj projekata skriniranih kroz ORRI alat",
        "Number of projects screened through the ORRI Tool",
        "Da li se projekti usmeravaju kroz ORRI pregled",
        "Whether projects are routed through the ORRI review",
        "Prijave projekata, ORRI koordinacija",
        "Project intake forms, ORRI coordination records",
        "Kvartalno",
        "Quarterly",
        "Svi AI/visoko-uticajni projekti",
        "All AI-supported or higher-impact projects",
      ),
      k(
        "1.2",
        "Udeo projekata sa završenim Phase-Based Checklist-om",
        "Share of projects with completed Phase-Based Checklist",
        "Da li projekti završavaju centralni checklist",
        "Whether projects complete the central checklist",
        "Kompletirane checkliste, dossier-i",
        "Completed checklists, governance dossiers",
        "Kvartalno",
        "Quarterly",
        "Visok za sve relevantne projekte",
        "High for all relevant projects",
      ),
      k(
        "1.3",
        "Broj pilot use-case-ova u kojima se alat testira",
        "Number of pilot use cases testing the Tool",
        "Praćenje pilot implementacije",
        "Track pilot implementation",
        "Pilot izveštaji",
        "Pilot project records",
        "Nakon svake pilot faze",
        "At end of each pilot phase",
        "Prema projektu",
        "As defined by the project",
      ),
      k(
        "1.4",
        "Broj projekata koji koriste specifične šablone",
        "Number of projects using specific templates",
        "Koji delovi alata se najviše koriste",
        "Which parts of the Tool are used most",
        "Evidencije šablona",
        "Template completion records",
        "Kvartalno / polugodišnje",
        "Quarterly or semi-annually",
        "Šabloni tamo gde je pitanje relevantno",
        "Templates used where relevant",
      ),
    ],
  },
  {
    id: "2",
    title: bi("Kvalitet i pravovremenost pregleda", "Review Quality and Timeliness"),
    description: bi(
      "Da li se pitanja identifikuju dovoljno rano da utiču na odluke.",
      "Whether issues are identified early enough to influence decisions.",
    ),
    kpis: [
      k(
        "2.1",
        "Broj završenih pregleda (etika, privatnost, prava, AI, vendor)",
        "Number of ethics/privacy/rights/AI/vendor reviews completed",
        "Koliko često se sprovode strukturirani pregledi",
        "How often structured reviews are carried out",
        "Beleške pregleda, ORRI koordinacija",
        "Review notes, ORRI coordination records",
        "Kvartalno",
        "Quarterly",
        "Indikativni cilj: 3 (SAFEGUARD-DH Annex I)",
        "Indicative target: 3 (SAFEGUARD-DH Annex I)",
      ),
      k(
        "2.2",
        "Udeo pregleda završenih pre ključnih odluka",
        "Share of reviews completed before key decisions",
        "Da li se pregled radi na vreme",
        "Whether review happens early enough",
        "Phase-gate zapisi, vremenska linija",
        "Phase-gate records, project timelines",
        "Kvartalno",
        "Quarterly",
        "Većina pre selekcije/objavljivanja",
        "Most before selection/publication",
      ),
      k(
        "2.3",
        "Broj pitanja identifikovanih pre objavljivanja",
        "Number of issues identified before publication",
        "Da li alat pomaže u ranom otkrivanju rizika",
        "Whether the Tool helps detect risks early",
        "Registri rizika, pregledi",
        "Risk registers, review notes",
        "Pri objavljivanju i post-projektu",
        "At publication and post-project",
        "Nema fiksnog cilja — učenje",
        "No fixed target — for learning",
      ),
      k(
        "2.4",
        "Broj projekata koji nastavljaju sa uslovima",
        "Number of projects proceeding with conditions",
        "Slučajevi sa merama zaštite / ograničenjima",
        "Cases continuing with safeguards / restrictions",
        "Phase-gate odluke",
        "Phase-gate decisions",
        "Kvartalno",
        "Quarterly",
        "Bez fiksnog cilja",
        "No fixed target",
      ),
    ],
  },
  {
    id: "3",
    title: bi("Dokumentacija i sledljivost", "Documentation and Traceability"),
    description: bi(
      "Da li institucija vodi jasnu evidenciju odluka i rizika.",
      "Whether the institution keeps a clear record of decisions and risks.",
    ),
    kpis: [
      k(
        "3.1",
        "Udeo projekata sa phase-gate zapisima",
        "Share of projects with phase-gate decision records",
        "Da li se odluke dokumentuju na kraju svake faze",
        "Whether decisions are recorded at each phase-gate",
        "Phase-gate zapisi",
        "Phase-gate records",
        "Kvartalno / po fazi",
        "Quarterly / per phase",
        "Svi relevantni projekti",
        "All relevant projects",
      ),
      k(
        "3.2",
        "Broj kompletiranih Decision Record šablona",
        "Number of completed Decision Record templates",
        "Da li se ključne odluke formalno evidentiraju",
        "Whether key decisions are formally recorded",
        "Šabloni odluka",
        "Decision Record templates",
        "Kvartalno",
        "Quarterly",
        "Prema značaju odluke",
        "Per decision significance",
      ),
      k(
        "3.3",
        "Broj ORRI Governance Dossier-a",
        "Number of ORRI Governance Dossiers",
        "Prisustvo dossiera za značajne projekte",
        "Presence of dossiers for significant projects",
        "Dossier registar",
        "Dossier registry",
        "Na zatvaranju projekta",
        "At project closure",
        "Svi projekti srednjeg i visokog rizika",
        "All medium- and high-risk projects",
      ),
      k(
        "3.4",
        "Broj nepotpunih/zastarelih zapisa",
        "Number of incomplete or outdated records",
        "Identifikacija dokumentacionih praznina",
        "Identify documentation gaps",
        "Dokumentacioni audit",
        "Documentation audit",
        "Polugodišnje / godišnje",
        "Semi-annually / annually",
        "Opadajući trend",
        "Decrease over time",
      ),
    ],
  },
  {
    id: "4",
    title: bi("Eskalacija i institucionalna responzivnost", "Escalation and Institutional Responsiveness"),
    description: bi(
      "Da li ozbiljna pitanja dobijaju odgovor i vlasništvo.",
      "Whether serious issues get ownership and response.",
    ),
    kpis: [
      k(
        "4.1",
        "Broj eskaliranih pitanja po tipu",
        "Number of escalated issues by type",
        "Razumevanje obrazaca eskalacije",
        "Understand escalation patterns",
        "Log eskalacija",
        "Escalation log",
        "Kvartalno",
        "Quarterly",
        "Bez fiksnog cilja",
        "No fixed target",
      ),
      k(
        "4.2",
        "Udeo eskaliranih pitanja rešenih pre naredne faze",
        "Share of escalated issues resolved before next phase",
        "Da li eskalacija vodi ka akciji",
        "Whether escalation leads to action",
        "Log eskalacija",
        "Escalation log",
        "Kvartalno",
        "Quarterly",
        "Institucionalno definisano",
        "Institutionally defined",
      ),
      k(
        "4.3",
        "Vreme do razrešenja eskaliranih pitanja",
        "Time to resolution of escalated issues",
        "Praćenje trajanja razrešenja",
        "Track resolution time",
        "Log eskalacija, datumi",
        "Escalation log, dates",
        "Kvartalno",
        "Quarterly",
        "Institucionalno definisano",
        "Institutionally defined",
      ),
      k(
        "4.4",
        "Broj nerešenih pitanja visokog značaja",
        "Number of unresolved high-significance issues",
        "Nema otvorenih ozbiljnih pitanja bez vlasnika",
        "No serious open issues without owner",
        "Registar rizika, izveštaji",
        "Risk register, management reports",
        "Mesečno za aktivne / kvartalno",
        "Monthly for active / quarterly",
        "0 bez dodeljenog vlasnika",
        "0 without assigned ownership",
      ),
    ],
  },
  {
    id: "5",
    title: bi("Uključivanje stejkholdera", "Stakeholder Engagement and Inclusion"),
    description: bi(
      "Da li se relevantne zajednice i stručnjaci konsultuju.",
      "Whether relevant communities and experts are consulted.",
    ),
    kpis: [
      k(
        "5.1",
        "Broj konsultovanih stejkholdera / eksperata",
        "Number of stakeholders / experts consulted",
        "Praćenje eksternih inputa",
        "Track external input",
        "Zapisi konsultacija",
        "Consultation records",
        "Po projektu",
        "Per project",
        "Prema tipu projekta",
        "Per project type",
      ),
      k(
        "5.2",
        "Broj projekata sa dokumentovanim angažovanjem zajednica",
        "Number of projects with documented community engagement",
        "Da li se osetljivi projekti angažuju sa zajednicama",
        "Whether sensitive projects engage communities",
        "Etička checklista, engagement plan",
        "Ethics checklist, engagement plan",
        "Faze planiranja/selekcije/objavljivanja",
        "Planning, selection, publication phases",
        "Svi osetljivi projekti",
        "All sensitive projects",
      ),
      k(
        "5.3",
        "Broj odluka pod uticajem stejkholder inputa",
        "Number of decisions influenced by stakeholder input",
        "Da li je angažovanje suštinsko, a ne formalno",
        "Whether engagement is meaningful, not formal",
        "Zapisi angažovanja i odluka",
        "Engagement and decision records",
        "Po projektu",
        "Per project",
        "Prema kontekstu",
        "Contextually defined",
      ),
    ],
  },
  {
    id: "6",
    title: bi("Izgradnja kapaciteta i upotrebljivost", "Capacity Building and Usability"),
    description: bi(
      "Da li osoblje razume alat i oseća se sigurno u njegovoj upotrebi.",
      "Whether staff understands the tool and feels confident using it.",
    ),
    kpis: [
      k(
        "6.1",
        "Broj obučenih zaposlenih",
        "Number of staff trained",
        "Praćenje pokrivenosti obukom",
        "Training coverage",
        "Evidencije obuka",
        "Training records",
        "Polugodišnje",
        "Semi-annually",
        "Sav relevantan personal",
        "All relevant staff",
      ),
      k(
        "6.2",
        "Udeo koji ocenjuje alat/obuku kao koristan",
        "Share rating Tool/training as useful",
        "Da li je alat upotrebljiv u praksi",
        "Whether the Tool is usable in practice",
        "Ankete povratnih informacija",
        "Feedback surveys",
        "Nakon obuke/pilota",
        "After training / pilot",
        "70% (SAFEGUARD-DH Annex I)",
        "70% (SAFEGUARD-DH Annex I)",
      ),
      k(
        "6.3",
        "Broj zahteva osoblja za pojašnjenje",
        "Number of staff requests for clarification",
        "Koji delovi alata su nejasni",
        "Which parts of the Tool are unclear",
        "Helpdesk / ORRI koordinacija",
        "Helpdesk / ORRI coordination",
        "Kvartalno",
        "Quarterly",
        "Opadajući trend",
        "Decreasing trend",
      ),
    ],
  },
  {
    id: "7",
    title: bi("Post-publikaciono praćenje i korekcije", "Post-Publication Monitoring and Correction"),
    description: bi(
      "Da li institucija ostaje odgovorna nakon objavljivanja.",
      "Whether the institution remains accountable after publication.",
    ),
    kpis: [
      k(
        "7.1",
        "Broj post-publikacionih korekcija",
        "Number of post-publication corrections",
        "Praćenje ispravki nakon objavljivanja",
        "Track corrections after publication",
        "Log korekcija",
        "Correction log",
        "Kvartalno",
        "Quarterly",
        "Bez fiksnog cilja",
        "No fixed target",
      ),
      k(
        "7.2",
        "Broj zahteva za takedown / promenu pristupa",
        "Number of takedown / access-change requests",
        "Praćenje javnih zahteva",
        "Track public requests",
        "Log zahteva",
        "Request log",
        "Kvartalno",
        "Quarterly",
        "Svi zabeleženi",
        "All logged and reviewed",
      ),
      k(
        "7.3",
        "Udeo pitanja rešenih u zadatom roku",
        "Share of issues resolved within defined timeframe",
        "Institucionalna responzivnost",
        "Institutional responsiveness",
        "Log pitanja, datumi",
        "Issue log, response dates",
        "Kvartalno",
        "Quarterly",
        "Institucionalno definisano",
        "Institutionally defined",
      ),
      k(
        "7.4",
        "Broj tipova pitanja koji se ponavljaju",
        "Number of recurring issue types",
        "Identifikacija sistemskih problema",
        "Identify systemic issues",
        "Analiza logova",
        "Log analysis",
        "Polugodišnje",
        "Semi-annually",
        "Opadajući trend",
        "Decreasing trend",
      ),
    ],
  },
  {
    id: "8",
    title: bi("Održivost i institucionalno usvajanje", "Sustainability and Institutional Uptake"),
    description: bi(
      "Da li alat postaje deo stalne prakse institucije.",
      "Whether the Tool becomes part of ongoing institutional practice.",
    ),
    kpis: [
      k(
        "8.1",
        "Formalno institucionalno usvajanje alata",
        "Formal institutional adoption of the Tool",
        "Ugrađenost u politiku institucije",
        "Embedding into institutional policy",
        "Odluka menadžmenta",
        "Management decision, policy adoption",
        "Jednokratno / po promeni",
        "One-off / on change",
        "Indikativni cilj: 1 (Annex I)",
        "Indicative target: 1 (Annex I)",
      ),
      k(
        "8.2",
        "Plan kontinuirane upotrebe nakon projekta",
        "Post-project continuity plan",
        "Da li alat opstaje nakon projekta",
        "Whether the Tool persists after project end",
        "Plan održivosti",
        "Sustainability plan",
        "Na zatvaranju projekta",
        "At project closure",
        "Postoji plan",
        "Plan exists",
      ),
      k(
        "8.3",
        "Broj aktivnosti diseminacije",
        "Number of dissemination activities",
        "Komunikacija i deljenje znanja",
        "Communication and knowledge sharing",
        "Prezentacije, publikacije, događaji",
        "Presentations, publications, events",
        "Kvartalno",
        "Quarterly",
        "Indikativni cilj: 10 (Annex I)",
        "Indicative target: 10 (Annex I)",
      ),
    ],
  },
];

export function allKpis(): Kpi[] {
  return kpiAreas.flatMap((a) => a.kpis);
}
